-- KinPress editorial starter content (run after 001 + 002 migrations)
-- Safe to re-run: uses slug-based upserts

insert into public.categories (name, slug, sort_order, is_active)
values
  ('News', 'news', 1, true),
  ('Culture', 'culture', 2, true),
  ('Politics', 'politics', 3, true),
  ('Business', 'business', 4, true),
  ('History', 'history', 5, true),
  ('Arts', 'arts', 6, true),
  ('Community', 'community', 7, true),
  ('Opinion', 'opinion', 8, true)
on conflict (slug) do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_active = true;

insert into public.articles (
  title,
  slug,
  excerpt,
  summary,
  body,
  category_name,
  tags,
  author_name,
  source_name,
  source_url,
  image_url,
  cover_image_url,
  status,
  published_at,
  is_featured,
  editor_pick,
  reading_time,
  region,
  topic,
  article_kind
)
values
(
  'Black-owned businesses are reshaping Main Street recovery',
  'black-owned-business-growth',
  'KinPress examines how Black entrepreneurs are expanding retail, food, and professional services—and what community investment makes possible.',
  'KinPress examines how Black entrepreneurs are expanding retail, food, and professional services—and what community investment makes possible.',
  'Across U.S. cities, Black-owned businesses continue to anchor neighborhood economies. KinPress reporting highlights cooperative models, credit access programs, and mentorship networks that help founders scale without leaving their communities.

This overview is evergreen context—not a claim about a single breaking event. It is meant to support readers tracking long-term economic patterns in Black business life.',
  'Business',
  array['business', 'entrepreneurship', 'economy'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&q=80',
  'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&q=80',
  'published',
  now() - interval '2 days',
  true,
  true,
  5,
  'national',
  'business',
  'kinpress_original'
),
(
  'Inside HBCU labs where student innovators build the future',
  'hbcu-innovation-labs',
  'From robotics to public health tech, Historically Black Colleges and Universities are producing research pipelines that deserve sustained funding and industry partnership.',
  'From robotics to public health tech, Historically Black Colleges and Universities are producing research pipelines that deserve sustained funding and industry partnership.',
  'HBCU campuses have long been sites of invention under resource constraints. KinPress spotlights student-led projects in engineering, agriculture, and digital media that translate classroom learning into community tools.

Readers should treat this as an explanatory feature on institutional innovation—not live lab results from a specific unpublished study.',
  'Culture',
  array['hbcu', 'education', 'innovation'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&q=80',
  'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&q=80',
  'published',
  now() - interval '3 days',
  true,
  false,
  6,
  'national',
  'education',
  'kinpress_original'
),
(
  'Voting rights organizing meets a new generation of civic leaders',
  'voting-rights-civic-participation',
  'Grassroots groups are pairing voter education with local issue campaigns, emphasizing year-round participation beyond election seasons.',
  'Grassroots groups are pairing voter education with local issue campaigns, emphasizing year-round participation beyond election seasons.',
  'KinPress summarizes enduring civic engagement strategies: town halls, ballot education, protection for election workers, and coalitions that connect voting to housing, transit, and public safety.

This article does not report tonight''s election results. It documents the structural work that keeps democracy accessible in Black communities.',
  'Politics',
  array['voting', 'civic', 'democracy'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1541872706-689e0924f199?w=1200&q=80',
  'https://images.unsplash.com/photo-1541872706-689e0924f199?w=1200&q=80',
  'published',
  now() - interval '4 days',
  false,
  true,
  5,
  'national',
  'politics',
  'kinpress_original'
),
(
  'Why Black maternal health advocates demand systemic reform',
  'black-maternal-health-advocacy',
  'Community doulas, midwives, and policy researchers outline what respectful, culturally competent care should look like in hospitals and clinics.',
  'Community doulas, midwives, and policy researchers outline what respectful, culturally competent care should look like in hospitals and clinics.',
  'Disparities in maternal outcomes remain a national crisis. KinPress explains how peer support networks, Medicaid expansion, and accountability measures fit into a long reform agenda led by Black women health workers.

Figures cited in public health literature should be verified against primary sources; this piece frames the advocacy landscape rather than announcing new clinical trials.',
  'News',
  array['health', 'maternal', 'policy'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&q=80',
  'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&q=80',
  'published',
  now() - interval '5 days',
  false,
  false,
  6,
  'national',
  'health',
  'kinpress_original'
),
(
  'Black art institutions are redefining who gets to curate the canon',
  'black-art-institutions',
  'Museums and collectives are centering Black curators, living artists, and community archives in exhibitions that challenge narrow definitions of fine art.',
  'Museums and collectives are centering Black curators, living artists, and community archives in exhibitions that challenge narrow definitions of fine art.',
  'From regional galleries to major institutions, Black-led programming is expanding what counts as heritage and contemporary practice. KinPress notes residency models, acquisition funds, and education partnerships that keep artists paid and credited.

This is cultural analysis—not a review of a single opening night.',
  'Arts',
  array['arts', 'museums', 'culture'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1460668260487-6a9efab20a26?w=1200&q=80',
  'https://images.unsplash.com/photo-1460668260487-6a9efab20a26?w=1200&q=80',
  'published',
  now() - interval '6 days',
  false,
  true,
  5,
  'national',
  'arts',
  'kinpress_original'
),
(
  'Reparations debates return to city halls with new fiscal frameworks',
  'reparations-debates-local-policy',
  'Researchers and elected officials are testing targeted housing, education, and business programs as municipalities study restorative economic policy.',
  'Researchers and elected officials are testing targeted housing, education, and business programs as municipalities study restorative economic policy.',
  'KinPress maps how reparations conversations differ by region: study commissions, pilot cash programs, and land return initiatives each carry distinct legal and political constraints.

Readers should consult official city records for the latest votes; this summary explains recurring policy designs.',
  'Politics',
  array['reparations', 'policy', 'justice'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1200&q=80',
  'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1200&q=80',
  'published',
  now() - interval '7 days',
  false,
  false,
  5,
  'local',
  'justice',
  'kinpress_original'
),
(
  'Neighborhood coalitions model mutual aid beyond headlines',
  'local-black-community-organizing',
  'Food networks, tenant unions, and safety teams show how hyperlocal organizing sustains families when larger systems move slowly.',
  'Food networks, tenant unions, and safety teams show how hyperlocal organizing sustains families when larger systems move slowly.',
  'KinPress profiles recurring structures in community organizing: transparent budgeting, multilingual outreach, and partnerships with churches and schools.

These patterns appear in many cities; this article does not claim a single new program launch unless verified locally.',
  'Community',
  array['organizing', 'mutual-aid', 'local'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&q=80',
  'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&q=80',
  'published',
  now() - interval '8 days',
  false,
  false,
  4,
  'local',
  'community',
  'kinpress_original'
),
(
  'Black founders are building AI tools with accountability at the center',
  'black-tech-founders-ai',
  'Entrepreneurs stress data dignity, consent, and bias testing as they ship products for education, finance, and creative work.',
  'Entrepreneurs stress data dignity, consent, and bias testing as they ship products for education, finance, and creative work.',
  'KinPress surveys design principles emerging from Black-led tech studios: community advisory boards, open documentation, and refusal to sell surveillance packages to schools.

Product names and funding rounds change quickly—treat this as a thematic guide to founder ethics.',
  'Business',
  array['technology', 'startups', 'ai'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&q=80',
  'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&q=80',
  'published',
  now() - interval '9 days',
  false,
  false,
  5,
  'national',
  'business',
  'kinpress_original'
),
(
  'Diaspora festivals keep language, food, and memory alive abroad',
  'african-diaspora-culture-festivals',
  'Annual gatherings in Europe, the Caribbean, and North America connect generations through music, cuisine, and oral history projects.',
  'Annual gatherings in Europe, the Caribbean, and North America connect generations through music, cuisine, and oral history projects.',
  'KinPress celebrates diaspora cultural life as ongoing tradition—storytelling stages, fashion markets, and archive digitization efforts that link continents.

Event dates vary by city; confirm schedules with organizers before traveling.',
  'Culture',
  array['diaspora', 'festivals', 'heritage'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1506157786151-b8493531f3f0?w=1200&q=80',
  'https://images.unsplash.com/photo-1506157786151-b8493531f3f0?w=1200&q=80',
  'published',
  now() - interval '10 days',
  false,
  false,
  4,
  'diaspora',
  'culture',
  'kinpress_original'
),
(
  'Education equity campaigns push for counselors, books, and fair funding',
  'education-equity-campaigns',
  'Students and parents demand culturally relevant curricula, mental health staff, and transparent district budgets.',
  'Students and parents demand culturally relevant curricula, mental health staff, and transparent district budgets.',
  'KinPress outlines common equity demands appearing in school board testimony nationwide: discipline reform, teacher diversity, and repair of aging buildings in majority-Black districts.

This feature supports civic literacy; it is not a scorecard for a specific district vote.',
  'News',
  array['education', 'schools', 'equity'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1503676260728-1c00da280a02?w=1200&q=80',
  'https://images.unsplash.com/photo-1503676260728-1c00da280a02?w=1200&q=80',
  'published',
  now() - interval '11 days',
  false,
  false,
  5,
  'national',
  'education',
  'kinpress_original'
),
(
  'Labor unions and Black workers organize for safer warehouses',
  'labor-unions-black-workers',
  'Warehouse, transit, and healthcare workers describe how collective bargaining addresses pace-of-work injuries and unfair scheduling.',
  'Warehouse, transit, and healthcare workers describe how collective bargaining addresses pace-of-work injuries and unfair scheduling.',
  'KinPress explains why labor coverage belongs in Black news: occupational segregation, retaliation risks, and cross-racial solidarity on picket lines.

Union election outcomes should be verified with NLRB filings; this article teaches structural context.',
  'Business',
  array['labor', 'unions', 'work'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&q=80',
  'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&q=80',
  'published',
  now() - interval '12 days',
  false,
  false,
  5,
  'national',
  'business',
  'kinpress_original'
),
(
  'Culture critics revisit the albums that shaped a decade of Black sound',
  'culture-music-criticism-decade',
  'Writers debate craftsmanship, sampling ethics, and how streaming changed what gets called a classic.',
  'Writers debate craftsmanship, sampling ethics, and how streaming changed what gets called a classic.',
  'KinPress publishes criticism as conversation—multiple voices, clear disclosures, and respect for artists'' creative control.

This is arts commentary, not a chart of this week''s sales.',
  'Arts',
  array['music', 'criticism', 'culture'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80',
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80',
  'published',
  now() - interval '13 days',
  false,
  true,
  6,
  'national',
  'arts',
  'kinpress_original'
),
(
  'Historic Black newspapers inform today''s digital newsrooms',
  'historic-black-press-archives',
  'Archivists digitize abolition-era sheets and twentieth-century weeklies so reporters can trace community debates across time.',
  'Archivists digitize abolition-era sheets and twentieth-century weeklies so reporters can trace community debates across time.',
  'KinPress connects history desks with contemporary reporting: how archive access shapes investigations into land policy, church life, and migration.

No single archive launch is claimed here—this is a guide to why history matters for newsrooms.',
  'History',
  array['history', 'archives', 'media'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1481627834876-d7830162f566?w=1200&q=80',
  'https://images.unsplash.com/photo-1481627834876-d7830162f566?w=1200&q=80',
  'published',
  now() - interval '14 days',
  false,
  false,
  5,
  'national',
  'history',
  'kinpress_original'
),
(
  'Opinion: Joy is a reporting beat, not a footnote',
  'opinion-joy-as-reporting-beat',
  'KinPress argues that celebrations, humor, and rest stories are essential—not optional—when covering Black life with dignity.',
  'KinPress argues that celebrations, humor, and rest stories are essential—not optional—when covering Black life with dignity.',
  'Editorial boards too often treat trauma as the default frame. This opinion piece invites readers to expect rigor in stories about weddings, sports leagues, and block parties too.

Views belong to KinPress Opinion; they do not speak for every contributor.',
  'Opinion',
  array['opinion', 'culture', 'editorial'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&q=80',
  'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&q=80',
  'published',
  now() - interval '15 days',
  false,
  false,
  4,
  'national',
  'opinion',
  'kinpress_original'
),
(
  'Justice reform coalitions focus on public defense and record relief',
  'justice-reform-public-defense',
  'Legal aid groups pair expungement clinics with policy pushes to end cash bail and strengthen oversight of policing contracts.',
  'Legal aid groups pair expungement clinics with policy pushes to end cash bail and strengthen oversight of policing contracts.',
  'KinPress documents long-horizon justice work—court watching, civilian review, and reentry services—without sensationalizing individual cases.

Verify case outcomes in court records; this article explains movement architecture.',
  'Politics',
  array['justice', 'legal', 'reform'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1589829545856-d10a557a4e99?w=1200&q=80',
  'https://images.unsplash.com/photo-1589829545856-d10a557a4e99?w=1200&q=80',
  'published',
  now() - interval '16 days',
  false,
  false,
  5,
  'national',
  'justice',
  'kinpress_original'
),
(
  'Curated read: Black Enterprise on building generational wealth',
  'curated-black-enterprise-wealth',
  'KinPress summary: practitioners highlight estate planning, employee ownership, and community development finance as pillars of multigenerational stability.',
  'KinPress summary: practitioners highlight estate planning, employee ownership, and community development finance as pillars of multigenerational stability.',
  'This KinPress curated brief offers context and questions for readers before they visit the original publisher. We do not republish the full article.

KinPress excerpt only. For complete reporting, follow the canonical link below.',
  'Business',
  array['business', 'wealth', 'curated'],
  'KinPress Editorial',
  'Black Enterprise',
  'https://www.blackenterprise.com',
  'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80',
  'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80',
  'published',
  now() - interval '17 days',
  false,
  false,
  3,
  'national',
  'business',
  'curated_external'
),
(
  'Curated read: NPR Code Switch on language and identity',
  'curated-npr-code-switch-language',
  'KinPress summary: journalists explore how dialect, naming, and translation shape belonging for Black communities in multilingual cities.',
  'KinPress summary: journalists explore how dialect, naming, and translation shape belonging for Black communities in multilingual cities.',
  'A short KinPress guide to the themes in the original piece—useful for classroom discussion and newsroom training.

Full text and audio remain at the source link; KinPress does not copy them here.',
  'Culture',
  array['culture', 'language', 'curated'],
  'KinPress Editorial',
  'NPR Code Switch',
  'https://www.npr.org/sections/codeswitch',
  'https://images.unsplash.com/photo-1524995463492-9972dceb5c96?w=1200&q=80',
  'https://images.unsplash.com/photo-1524995463492-9972dceb5c96?w=1200&q=80',
  'published',
  now() - interval '18 days',
  false,
  false,
  3,
  'national',
  'culture',
  'curated_external'
),
(
  'Community voices: letters on what local news should cover next',
  'community-letters-local-news',
  'Readers ask KinPress for more transit reporting, high school sports, and transparent coverage of development deals.',
  'Readers ask KinPress for more transit reporting, high school sports, and transparent coverage of development deals.',
  'Selected letters are edited for clarity. They represent reader perspectives, not KinPress institutional policy.

Want to respond? Submit through your profile after signing in.',
  'Community',
  array['community', 'letters', 'local'],
  'KinPress Editorial',
  null,
  null,
  'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&q=80',
  'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&q=80',
  'published',
  now() - interval '19 days',
  false,
  false,
  4,
  'local',
  'community',
  'kinpress_original'
)
on conflict (slug) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  summary = excluded.summary,
  body = excluded.body,
  category_name = excluded.category_name,
  tags = excluded.tags,
  author_name = excluded.author_name,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  image_url = excluded.image_url,
  cover_image_url = excluded.cover_image_url,
  status = excluded.status,
  published_at = excluded.published_at,
  is_featured = excluded.is_featured,
  editor_pick = excluded.editor_pick,
  reading_time = excluded.reading_time,
  region = excluded.region,
  topic = excluded.topic,
  article_kind = excluded.article_kind,
  updated_at = now();
