-- KinPress verified starter data.
-- This file intentionally avoids fake articles, fake authors, and fake dates.
-- News should be ingested from approved RSS/API sources via /api/ingest/news.
-- Resource, opportunity, and event rows below are source-attributed utility records.

insert into public.categories (name, slug, sort_order, is_active)
values
  ('Top Stories', 'top-stories', 1, true),
  ('Politics', 'politics', 2, true),
  ('Culture', 'culture', 3, true),
  ('Business', 'business', 4, true),
  ('Health', 'health', 5, true),
  ('Tech', 'tech', 6, true),
  ('History', 'history', 7, true),
  ('Local', 'local', 8, true),
  ('Resources', 'resources', 9, true),
  ('Opinion', 'opinion', 10, true)
on conflict (slug) do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_active = true;

insert into public.resources (
  title,
  organization,
  description,
  category,
  location,
  region,
  eligibility,
  cost,
  format,
  source_url,
  date_verified,
  tags,
  is_verified,
  status
)
values
(
  'SBA funding programs',
  'U.S. Small Business Administration',
  'Official SBA guide to loans, investment capital, disaster assistance, surety bonds, and grants for small businesses.',
  'business funding',
  'United States',
  'national',
  'Eligibility varies by program. Review requirements at the official SBA source.',
  'Varies',
  'Guide',
  'https://www.sba.gov/funding-programs',
  current_date,
  array['business', 'funding', 'sba'],
  true,
  'published'
),
(
  'NAACP resources',
  'NAACP',
  'Official NAACP resources and action materials for civic engagement, advocacy, health, education, and community organizing.',
  'civil rights',
  'United States',
  'national',
  'Public resource.',
  'Free',
  'Resource hub',
  'https://naacp.org/resources',
  current_date,
  array['civil-rights', 'advocacy', 'community'],
  true,
  'published'
),
(
  'National Urban League programs',
  'National Urban League',
  'Official National Urban League program information covering jobs, education, housing, entrepreneurship, and justice.',
  'community organizations',
  'United States',
  'national',
  'Availability varies by affiliate and program.',
  'Varies',
  'Program directory',
  'https://nul.org/programs',
  current_date,
  array['urban-league', 'jobs', 'housing'],
  true,
  'published'
),
(
  'HUD housing counseling',
  'U.S. Department of Housing and Urban Development',
  'HUD tool for finding approved housing counseling agencies that can support renters, homeowners, and homebuyers.',
  'housing support',
  'United States',
  'national',
  'Public resource.',
  'Free or low cost',
  'Search tool',
  'https://www.hud.gov/findacounselor',
  current_date,
  array['housing', 'hud', 'counseling'],
  true,
  'published'
),
(
  'ByBlack business directory',
  'U.S. Black Chambers, Inc.',
  'Directory for discovering Black-owned businesses and certified ByBlack businesses.',
  'black-owned businesses',
  'United States',
  'national',
  'Public resource.',
  'Free to search',
  'Directory',
  'https://byblack.us/',
  current_date,
  array['business-directory', 'black-owned', 'commerce'],
  true,
  'published'
)
on conflict (source_url) do update set
  title = excluded.title,
  organization = excluded.organization,
  description = excluded.description,
  category = excluded.category,
  location = excluded.location,
  region = excluded.region,
  eligibility = excluded.eligibility,
  cost = excluded.cost,
  format = excluded.format,
  date_verified = excluded.date_verified,
  tags = excluded.tags,
  is_verified = true,
  status = 'published',
  updated_at = now();

insert into public.opportunities (
  title,
  organization,
  description,
  category,
  deadline,
  eligibility,
  amount,
  location,
  region,
  source_url,
  date_verified,
  tags,
  is_verified,
  status
)
values
(
  'Grants.gov search for federal funding opportunities',
  'Grants.gov',
  'Official federal search portal for grant opportunities. Use keywords and eligibility filters to find current programs.',
  'grants',
  null,
  'Eligibility varies by grant.',
  'Varies',
  'United States',
  'national',
  'https://www.grants.gov/search-grants',
  current_date,
  array['grants', 'federal', 'funding'],
  true,
  'published'
),
(
  'UNCF scholarships',
  'UNCF',
  'Official UNCF scholarship search and application portal for students.',
  'scholarships',
  null,
  'Eligibility varies by scholarship.',
  'Varies',
  'United States',
  'national',
  'https://uncf.org/scholarships',
  current_date,
  array['scholarships', 'students', 'hbcu'],
  true,
  'published'
),
(
  'Thurgood Marshall College Fund scholarships',
  'Thurgood Marshall College Fund',
  'Official TMCF scholarship portal for students connected to publicly supported HBCUs and PBIs.',
  'scholarships',
  null,
  'Eligibility varies by scholarship.',
  'Varies',
  'United States',
  'national',
  'https://www.tmcf.org/students-alumni/scholarships/',
  current_date,
  array['scholarships', 'hbcu', 'students'],
  true,
  'published'
)
on conflict (source_url) do update set
  title = excluded.title,
  organization = excluded.organization,
  description = excluded.description,
  category = excluded.category,
  deadline = excluded.deadline,
  eligibility = excluded.eligibility,
  amount = excluded.amount,
  location = excluded.location,
  region = excluded.region,
  date_verified = excluded.date_verified,
  tags = excluded.tags,
  is_verified = true,
  status = 'published',
  updated_at = now();

insert into public.events (
  title,
  organizer,
  description,
  category,
  location,
  region,
  starts_at,
  ends_at,
  source_url,
  image_url,
  price,
  tags,
  is_verified,
  status
)
values
(
  'Eventbrite Black community events search',
  'Eventbrite',
  'Live Eventbrite search for Black community, culture, business, education, and networking events. Dates and ticket details are maintained at the source.',
  'community events',
  'United States',
  'local',
  null,
  null,
  'https://www.eventbrite.com/d/united-states/black-community/',
  null,
  'See source',
  array['events', 'community', 'culture'],
  true,
  'published'
),
(
  'National Museum of African American History and Culture events',
  'Smithsonian National Museum of African American History and Culture',
  'Official events calendar for exhibitions, public programs, and educational events from NMAAHC.',
  'history and culture',
  'Washington, DC',
  'national',
  null,
  null,
  'https://nmaahc.si.edu/events',
  null,
  'See source',
  array['history', 'culture', 'museum'],
  true,
  'published'
)
on conflict (source_url) do update set
  title = excluded.title,
  organizer = excluded.organizer,
  description = excluded.description,
  category = excluded.category,
  location = excluded.location,
  region = excluded.region,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  image_url = excluded.image_url,
  price = excluded.price,
  tags = excluded.tags,
  is_verified = true,
  status = 'published',
  updated_at = now();
